package com.example.model;
// Generated Jul 10, 2018 8:17:37 PM by Hibernate Tools 3.5.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "users", catalog = "demo")
public class Users implements java.io.Serializable {

	private Integer userId;
	private String userEmail;
	private String userPassword;
	private String userFirstName;
	private String userLastName;
	private String userCity;
	private String userState;
	private String userZip;
	private Boolean userEmailVerified;
	private Date userRegistrationDate;
	private String userVerificationCode;
	private String userIp;
	private String userPhone;
	private String userFax;
	private String userCountry;
	private String userAddress;
	private String userAddress2;

	public Users() {
	}

	public Users(String userEmail, String userPassword, String userFirstName, String userLastName, String userCity,
			String userState, String userZip, Boolean userEmailVerified, Date userRegistrationDate,
			String userVerificationCode, String userIp, String userPhone, String userFax, String userCountry,
			String userAddress, String userAddress2) {
		this.userEmail = userEmail;
		this.userPassword = userPassword;
		this.userFirstName = userFirstName;
		this.userLastName = userLastName;
		this.userCity = userCity;
		this.userState = userState;
		this.userZip = userZip;
		this.userEmailVerified = userEmailVerified;
		this.userRegistrationDate = userRegistrationDate;
		this.userVerificationCode = userVerificationCode;
		this.userIp = userIp;
		this.userPhone = userPhone;
		this.userFax = userFax;
		this.userCountry = userCountry;
		this.userAddress = userAddress;
		this.userAddress2 = userAddress2;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "UserID", unique = true, nullable = false)
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "UserEmail", length = 500)
	public String getUserEmail() {
		return this.userEmail;
	}

	public void setUserEmail(String userEmail) {
		this.userEmail = userEmail;
	}

	@Column(name = "UserPassword", length = 500)
	public String getUserPassword() {
		return this.userPassword;
	}

	public void setUserPassword(String userPassword) {
		this.userPassword = userPassword;
	}

	@Column(name = "UserFirstName", length = 50)
	public String getUserFirstName() {
		return this.userFirstName;
	}

	public void setUserFirstName(String userFirstName) {
		this.userFirstName = userFirstName;
	}

	@Column(name = "UserLastName", length = 50)
	public String getUserLastName() {
		return this.userLastName;
	}

	public void setUserLastName(String userLastName) {
		this.userLastName = userLastName;
	}

	@Column(name = "UserCity", length = 90)
	public String getUserCity() {
		return this.userCity;
	}

	public void setUserCity(String userCity) {
		this.userCity = userCity;
	}

	@Column(name = "UserState", length = 20)
	public String getUserState() {
		return this.userState;
	}

	public void setUserState(String userState) {
		this.userState = userState;
	}

	@Column(name = "UserZip", length = 12)
	public String getUserZip() {
		return this.userZip;
	}

	public void setUserZip(String userZip) {
		this.userZip = userZip;
	}

	@Column(name = "UserEmailVerified")
	public Boolean getUserEmailVerified() {
		return this.userEmailVerified;
	}

	public void setUserEmailVerified(Boolean userEmailVerified) {
		this.userEmailVerified = userEmailVerified;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UserRegistrationDate", length = 19)
	public Date getUserRegistrationDate() {
		return this.userRegistrationDate;
	}

	public void setUserRegistrationDate(Date userRegistrationDate) {
		this.userRegistrationDate = userRegistrationDate;
	}

	@Column(name = "UserVerificationCode", length = 100)
	public String getUserVerificationCode() {
		return this.userVerificationCode;
	}

	public void setUserVerificationCode(String userVerificationCode) {
		this.userVerificationCode = userVerificationCode;
	}

	@Column(name = "UserIP", length = 50)
	public String getUserIp() {
		return this.userIp;
	}

	public void setUserIp(String userIp) {
		this.userIp = userIp;
	}

	@Column(name = "UserPhone", length = 20)
	public String getUserPhone() {
		return this.userPhone;
	}

	public void setUserPhone(String userPhone) {
		this.userPhone = userPhone;
	}

	@Column(name = "UserFax", length = 20)
	public String getUserFax() {
		return this.userFax;
	}

	public void setUserFax(String userFax) {
		this.userFax = userFax;
	}

	@Column(name = "UserCountry", length = 20)
	public String getUserCountry() {
		return this.userCountry;
	}

	public void setUserCountry(String userCountry) {
		this.userCountry = userCountry;
	}

	@Column(name = "UserAddress", length = 100)
	public String getUserAddress() {
		return this.userAddress;
	}

	public void setUserAddress(String userAddress) {
		this.userAddress = userAddress;
	}

	@Column(name = "UserAddress2", length = 50)
	public String getUserAddress2() {
		return this.userAddress2;
	}

	public void setUserAddress2(String userAddress2) {
		this.userAddress2 = userAddress2;
	}

}
